//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueLabel.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Labeler.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CanSafelyCloseApp {
            get {
                return ResourceManager.GetString("CanSafelyCloseApp", resourceCulture);
            }
        }
        
        public static string Status_CopyingFiles {
            get {
                return ResourceManager.GetString("Status_CopyingFiles", resourceCulture);
            }
        }
        
        public static string Status_MovingFiles {
            get {
                return ResourceManager.GetString("Status_MovingFiles", resourceCulture);
            }
        }
        
        public static string Status_IHaveNoIdea {
            get {
                return ResourceManager.GetString("Status_IHaveNoIdea", resourceCulture);
            }
        }
        
        public static string Status_ErrorMovingExceptionCaught {
            get {
                return ResourceManager.GetString("Status_ErrorMovingExceptionCaught", resourceCulture);
            }
        }
        
        public static string Status_ErrorCopyingExceptionCuaght {
            get {
                return ResourceManager.GetString("Status_ErrorCopyingExceptionCuaght", resourceCulture);
            }
        }
        
        public static string ConfirmScreen_SelectOutputFile {
            get {
                return ResourceManager.GetString("ConfirmScreen_SelectOutputFile", resourceCulture);
            }
        }
        
        public static string Status_Finished {
            get {
                return ResourceManager.GetString("Status_Finished", resourceCulture);
            }
        }
        
        public static string WorkingOn_Nothing {
            get {
                return ResourceManager.GetString("WorkingOn_Nothing", resourceCulture);
            }
        }
        
        public static string Error_SaveOutputTo {
            get {
                return ResourceManager.GetString("Error_SaveOutputTo", resourceCulture);
            }
        }
        
        public static string PreviewArchive_FormatNotSupportedYet {
            get {
                return ResourceManager.GetString("PreviewArchive_FormatNotSupportedYet", resourceCulture);
            }
        }
        
        public static string Preview_PreviewMode {
            get {
                return ResourceManager.GetString("Preview_PreviewMode", resourceCulture);
            }
        }
        
        public static string Error_NoFilesLoaded {
            get {
                return ResourceManager.GetString("Error_NoFilesLoaded", resourceCulture);
            }
        }
        
        public static string Start_SelectFolderToSort {
            get {
                return ResourceManager.GetString("Start_SelectFolderToSort", resourceCulture);
            }
        }
        
        public static string Start_SelectOutputFolder {
            get {
                return ResourceManager.GetString("Start_SelectOutputFolder", resourceCulture);
            }
        }
        
        public static string Status_GettingFiles {
            get {
                return ResourceManager.GetString("Status_GettingFiles", resourceCulture);
            }
        }
        
        public static string Error_GettingFiles {
            get {
                return ResourceManager.GetString("Error_GettingFiles", resourceCulture);
            }
        }
        
        public static string AutoSort_ErrorOnFile {
            get {
                return ResourceManager.GetString("AutoSort_ErrorOnFile", resourceCulture);
            }
        }
        
        public static string AutoSort_Title {
            get {
                return ResourceManager.GetString("AutoSort_Title", resourceCulture);
            }
        }
        
        public static string AutoSort_Image {
            get {
                return ResourceManager.GetString("AutoSort_Image", resourceCulture);
            }
        }
        
        public static string AutoSort_Video {
            get {
                return ResourceManager.GetString("AutoSort_Video", resourceCulture);
            }
        }
        
        public static string AutoSort_Audio {
            get {
                return ResourceManager.GetString("AutoSort_Audio", resourceCulture);
            }
        }
        
        public static string AutoSort_Text {
            get {
                return ResourceManager.GetString("AutoSort_Text", resourceCulture);
            }
        }
        
        public static string AutoSort_Archive {
            get {
                return ResourceManager.GetString("AutoSort_Archive", resourceCulture);
            }
        }
        
        public static string AutoSort_Unknown {
            get {
                return ResourceManager.GetString("AutoSort_Unknown", resourceCulture);
            }
        }
        
        public static string AutoSort_Bigger {
            get {
                return ResourceManager.GetString("AutoSort_Bigger", resourceCulture);
            }
        }
        
        public static string AutoSort_Smaller {
            get {
                return ResourceManager.GetString("AutoSort_Smaller", resourceCulture);
            }
        }
        
        public static string Preview_FileNotSupported {
            get {
                return ResourceManager.GetString("Preview_FileNotSupported", resourceCulture);
            }
        }
        
        public static string Preview_ErrorWhilePreviewing {
            get {
                return ResourceManager.GetString("Preview_ErrorWhilePreviewing", resourceCulture);
            }
        }
        
        public static string Preview_FileInfo {
            get {
                return ResourceManager.GetString("Preview_FileInfo", resourceCulture);
            }
        }
        
        public static string PreviewAudio_UnknownTitle {
            get {
                return ResourceManager.GetString("PreviewAudio_UnknownTitle", resourceCulture);
            }
        }
        
        public static string PreviewAudio_UnknownArtist {
            get {
                return ResourceManager.GetString("PreviewAudio_UnknownArtist", resourceCulture);
            }
        }
        
        public static string PreviewImage_ZoomIn {
            get {
                return ResourceManager.GetString("PreviewImage_ZoomIn", resourceCulture);
            }
        }
        
        public static string PreviewImage_ZoomOut {
            get {
                return ResourceManager.GetString("PreviewImage_ZoomOut", resourceCulture);
            }
        }
        
        public static string PreviewArchive_Name {
            get {
                return ResourceManager.GetString("PreviewArchive_Name", resourceCulture);
            }
        }
        
        public static string PreviewArchive_Size {
            get {
                return ResourceManager.GetString("PreviewArchive_Size", resourceCulture);
            }
        }
        
        public static string PreviewArchive_Comment {
            get {
                return ResourceManager.GetString("PreviewArchive_Comment", resourceCulture);
            }
        }
        
        public static string ErrorScreen_Title {
            get {
                return ResourceManager.GetString("ErrorScreen_Title", resourceCulture);
            }
        }
        
        public static string ErrorScreen_SaveToFile {
            get {
                return ResourceManager.GetString("ErrorScreen_SaveToFile", resourceCulture);
            }
        }
        
        public static string ErrorScreen_Continue {
            get {
                return ResourceManager.GetString("ErrorScreen_Continue", resourceCulture);
            }
        }
        
        public static string LoadingScreen_Init {
            get {
                return ResourceManager.GetString("LoadingScreen_Init", resourceCulture);
            }
        }
        
        public static string LoadingScreen_WorkingOn {
            get {
                return ResourceManager.GetString("LoadingScreen_WorkingOn", resourceCulture);
            }
        }
        
        public static string ConfirmScreen_AutoClose {
            get {
                return ResourceManager.GetString("ConfirmScreen_AutoClose", resourceCulture);
            }
        }
        
        public static string ConfirmScreen_Confirmation {
            get {
                return ResourceManager.GetString("ConfirmScreen_Confirmation", resourceCulture);
            }
        }
        
        public static string ConfirmScreen_Back {
            get {
                return ResourceManager.GetString("ConfirmScreen_Back", resourceCulture);
            }
        }
        
        public static string ConfirmScreen_Continue {
            get {
                return ResourceManager.GetString("ConfirmScreen_Continue", resourceCulture);
            }
        }
        
        public static string ConfirmScreen_Title {
            get {
                return ResourceManager.GetString("ConfirmScreen_Title", resourceCulture);
            }
        }
        
        public static string PreviewMain_Finish {
            get {
                return ResourceManager.GetString("PreviewMain_Finish", resourceCulture);
            }
        }
        
        public static string PreviewMain_NewLabelButton {
            get {
                return ResourceManager.GetString("PreviewMain_NewLabelButton", resourceCulture);
            }
        }
        
        public static string PreviewMain_LabelName {
            get {
                return ResourceManager.GetString("PreviewMain_LabelName", resourceCulture);
            }
        }
        
        public static string PreviewMain_Add {
            get {
                return ResourceManager.GetString("PreviewMain_Add", resourceCulture);
            }
        }
        
        public static string PreviewMain_Content {
            get {
                return ResourceManager.GetString("PreviewMain_Content", resourceCulture);
            }
        }
        
        public static string PreviewMain_FileInfo {
            get {
                return ResourceManager.GetString("PreviewMain_FileInfo", resourceCulture);
            }
        }
        
        public static string PreviewMain_Back {
            get {
                return ResourceManager.GetString("PreviewMain_Back", resourceCulture);
            }
        }
        
        public static string About_Back {
            get {
                return ResourceManager.GetString("About_Back", resourceCulture);
            }
        }
        
        public static string About_About {
            get {
                return ResourceManager.GetString("About_About", resourceCulture);
            }
        }
        
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        public static string About_TechUsed {
            get {
                return ResourceManager.GetString("About_TechUsed", resourceCulture);
            }
        }
        
        public static string About_AboutDesc {
            get {
                return ResourceManager.GetString("About_AboutDesc", resourceCulture);
            }
        }
        
        public static string About_Visit {
            get {
                return ResourceManager.GetString("About_Visit", resourceCulture);
            }
        }
        
        public static string Start_About {
            get {
                return ResourceManager.GetString("Start_About", resourceCulture);
            }
        }
        
        public static string Start_Theme {
            get {
                return ResourceManager.GetString("Start_Theme", resourceCulture);
            }
        }
        
        public static string Start_ThemeSystemDefault {
            get {
                return ResourceManager.GetString("Start_ThemeSystemDefault", resourceCulture);
            }
        }
        
        public static string Start_LightTheme {
            get {
                return ResourceManager.GetString("Start_LightTheme", resourceCulture);
            }
        }
        
        public static string Start_DarkTheme {
            get {
                return ResourceManager.GetString("Start_DarkTheme", resourceCulture);
            }
        }
        
        public static string Start_UseBlur {
            get {
                return ResourceManager.GetString("Start_UseBlur", resourceCulture);
            }
        }
        
        public static string Start_Next {
            get {
                return ResourceManager.GetString("Start_Next", resourceCulture);
            }
        }
        
        public static string Start_Desc {
            get {
                return ResourceManager.GetString("Start_Desc", resourceCulture);
            }
        }
        
        public static string Start_Automation {
            get {
                return ResourceManager.GetString("Start_Automation", resourceCulture);
            }
        }
        
        public static string Start_AutomateManual {
            get {
                return ResourceManager.GetString("Start_AutomateManual", resourceCulture);
            }
        }
        
        public static string Start_AutomateDuration {
            get {
                return ResourceManager.GetString("Start_AutomateDuration", resourceCulture);
            }
        }
        
        public static string Start_AutomateImageSize {
            get {
                return ResourceManager.GetString("Start_AutomateImageSize", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileSize {
            get {
                return ResourceManager.GetString("Start_AutomateFileSize", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileType {
            get {
                return ResourceManager.GetString("Start_AutomateFileType", resourceCulture);
            }
        }
        
        public static string Start_AutomateDurationMin {
            get {
                return ResourceManager.GetString("Start_AutomateDurationMin", resourceCulture);
            }
        }
        
        public static string Start_AutomateDurationFormat {
            get {
                return ResourceManager.GetString("Start_AutomateDurationFormat", resourceCulture);
            }
        }
        
        public static string Start_AutomateDurationInfo {
            get {
                return ResourceManager.GetString("Start_AutomateDurationInfo", resourceCulture);
            }
        }
        
        public static string Start_AutomateImgSizeWidth {
            get {
                return ResourceManager.GetString("Start_AutomateImgSizeWidth", resourceCulture);
            }
        }
        
        public static string Start_AutomateImgSizeHeight {
            get {
                return ResourceManager.GetString("Start_AutomateImgSizeHeight", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileTypeUseExt {
            get {
                return ResourceManager.GetString("Start_AutomateFileTypeUseExt", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileSizeMin {
            get {
                return ResourceManager.GetString("Start_AutomateFileSizeMin", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileSizeBytes {
            get {
                return ResourceManager.GetString("Start_AutomateFileSizeBytes", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileSizeKB {
            get {
                return ResourceManager.GetString("Start_AutomateFileSizeKB", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileSizeKiB {
            get {
                return ResourceManager.GetString("Start_AutomateFileSizeKiB", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileSizeMB {
            get {
                return ResourceManager.GetString("Start_AutomateFileSizeMB", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileSizeMiB {
            get {
                return ResourceManager.GetString("Start_AutomateFileSizeMiB", resourceCulture);
            }
        }
        
        public static string Start_AutomateFİleSizeGB {
            get {
                return ResourceManager.GetString("Start_AutomateFİleSizeGB", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileSizeGiB {
            get {
                return ResourceManager.GetString("Start_AutomateFileSizeGiB", resourceCulture);
            }
        }
        
        public static string Start_AutomateFİleSizeTB {
            get {
                return ResourceManager.GetString("Start_AutomateFİleSizeTB", resourceCulture);
            }
        }
        
        public static string Start_AutomateFileSizeTiB {
            get {
                return ResourceManager.GetString("Start_AutomateFileSizeTiB", resourceCulture);
            }
        }
        
        public static string Start_OperationMode {
            get {
                return ResourceManager.GetString("Start_OperationMode", resourceCulture);
            }
        }
        
        public static string Start_OperationCopy {
            get {
                return ResourceManager.GetString("Start_OperationCopy", resourceCulture);
            }
        }
        
        public static string Start_OperationMove {
            get {
                return ResourceManager.GetString("Start_OperationMove", resourceCulture);
            }
        }
        
        public static string Start_FolderToProcess {
            get {
                return ResourceManager.GetString("Start_FolderToProcess", resourceCulture);
            }
        }
        
        public static string Start_SortInInput {
            get {
                return ResourceManager.GetString("Start_SortInInput", resourceCulture);
            }
        }
        
        public static string Start_OutputFolder {
            get {
                return ResourceManager.GetString("Start_OutputFolder", resourceCulture);
            }
        }
        
        public static string Start_SearchOptions {
            get {
                return ResourceManager.GetString("Start_SearchOptions", resourceCulture);
            }
        }
        
        public static string Start_IncludeSubfolders {
            get {
                return ResourceManager.GetString("Start_IncludeSubfolders", resourceCulture);
            }
        }
        
        public static string Start_UseFilters {
            get {
                return ResourceManager.GetString("Start_UseFilters", resourceCulture);
            }
        }
        
        public static string Start_Filters {
            get {
                return ResourceManager.GetString("Start_Filters", resourceCulture);
            }
        }
        
        public static string Start_FiltersDesc {
            get {
                return ResourceManager.GetString("Start_FiltersDesc", resourceCulture);
            }
        }
        
        public static string Start_ProjectAction {
            get {
                return ResourceManager.GetString("Start_ProjectAction", resourceCulture);
            }
        }
        
        public static string Start_ActionSubfolder {
            get {
                return ResourceManager.GetString("Start_ActionSubfolder", resourceCulture);
            }
        }
        
        public static string Start_ActionSubfolderMultiple {
            get {
                return ResourceManager.GetString("Start_ActionSubfolderMultiple", resourceCulture);
            }
        }
        
        public static string Start_ActionSubfolderMultipleDesc {
            get {
                return ResourceManager.GetString("Start_ActionSubfolderMultipleDesc", resourceCulture);
            }
        }
        
        public static string Start_ActionRename {
            get {
                return ResourceManager.GetString("Start_ActionRename", resourceCulture);
            }
        }
        
        public static string Start_ActionRenameFormat {
            get {
                return ResourceManager.GetString("Start_ActionRenameFormat", resourceCulture);
            }
        }
        
        public static string Start_ActionRenameFormatInfo {
            get {
                return ResourceManager.GetString("Start_ActionRenameFormatInfo", resourceCulture);
            }
        }
        
        public static string Start_ThemeButton {
            get {
                return ResourceManager.GetString("Start_ThemeButton", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string PreviewMain_FileInfo_ReadOnly {
            get {
                return ResourceManager.GetString("PreviewMain_FileInfo_ReadOnly", resourceCulture);
            }
        }
        
        public static string PreviewMain_FileInfo_LinksToNothing {
            get {
                return ResourceManager.GetString("PreviewMain_FileInfo_LinksToNothing", resourceCulture);
            }
        }
        
        public static string Import_ImportFile {
            get {
                return ResourceManager.GetString("Import_ImportFile", resourceCulture);
            }
        }
        
        public static string Import_DialogTitle {
            get {
                return ResourceManager.GetString("Import_DialogTitle", resourceCulture);
            }
        }
        
        public static string Import_FileTypeName {
            get {
                return ResourceManager.GetString("Import_FileTypeName", resourceCulture);
            }
        }
        
        public static string Start_Export {
            get {
                return ResourceManager.GetString("Start_Export", resourceCulture);
            }
        }
        
        public static string Start_ExportTitle {
            get {
                return ResourceManager.GetString("Start_ExportTitle", resourceCulture);
            }
        }
        
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        public static string Start_LastOpenedProjects {
            get {
                return ResourceManager.GetString("Start_LastOpenedProjects", resourceCulture);
            }
        }
        
        public static string Start_NoLastOpened {
            get {
                return ResourceManager.GetString("Start_NoLastOpened", resourceCulture);
            }
        }
        
        public static string Start_ClearLastOpened {
            get {
                return ResourceManager.GetString("Start_ClearLastOpened", resourceCulture);
            }
        }
        
        public static string Start_NewProject {
            get {
                return ResourceManager.GetString("Start_NewProject", resourceCulture);
            }
        }
        
        public static string Start_NewProjectDesc {
            get {
                return ResourceManager.GetString("Start_NewProjectDesc", resourceCulture);
            }
        }
        
        public static string Start_ImportProject {
            get {
                return ResourceManager.GetString("Start_ImportProject", resourceCulture);
            }
        }
        
        public static string Start_ImportProjectDesc {
            get {
                return ResourceManager.GetString("Start_ImportProjectDesc", resourceCulture);
            }
        }
    }
}
