name: BlueLabel Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup workloads
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ./src/BlueLabel.Android/BlueLabel.Android.csproj
    - name: Publish
      run: dotnet publish --no-restore ./src/BlueLabel.Android/BlueLabel.Android.csproj -c Release -f net8.0-android -o ./publish/android -r android-arm64
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: BlueLabel Android
          path: ./publish/android/
